### ISSUE TITLE
Add option to allow export of unsigned pacakges

### ISSUE THREAD

**Issue by ggatward** [RedHatSatellite/sat6_disconnected_tools#1]
By default the export fails if a package fails GPG check (including nokey). Need to add an override option to allow (or prompt) acceptance of an unsigned package as not all customers will have this requirement

**Comment by beav** [comment]
Which area fails during gpg check? Katello itself shouldn't care when writing pkgs to disk.

**Comment by ggatward** [comment]
Chris, its my script that fails if the GPG mismatches - katello doesn't care, but when I wrote this the customer requirement was that all packages are GPG verified. Since I'm now pushing this out beyond my customer env I need to make some allowances for others :-)

**Comment by ggatward** [comment]
Implemented in commit 677a528
